<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Skip405\\Kickbox\\WordPress\\' => array($vendorDir . '/skip405/kickbox-wordpress/src'),
);
