<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit60ed8c3fc8888f24f2ef6ea1c010bd52
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Skip405\\Kickbox\\WordPress\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Skip405\\Kickbox\\WordPress\\' => 
        array (
            0 => __DIR__ . '/..' . '/skip405/kickbox-wordpress/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit60ed8c3fc8888f24f2ef6ea1c010bd52::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit60ed8c3fc8888f24f2ef6ea1c010bd52::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit60ed8c3fc8888f24f2ef6ea1c010bd52::$classMap;

        }, null, ClassLoader::class);
    }
}
